//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreAddTech {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class SettingsUser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUser defaultInstance = ((SettingsUser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUser())));
        
        public static SettingsUser Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Система FoxPro
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система FoxPro")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FoxProPath {
            get {
                return ((string)(this["FoxProPath"]));
            }
            set {
                this["FoxProPath"] = value;
            }
        }
        
        /// <summary>
        /// Программа Book
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа Book")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookPath {
            get {
                return ((string)(this["BookPath"]));
            }
            set {
                this["BookPath"] = value;
            }
        }
        
        /// <summary>
        /// Cистема &quot;Создание триангуляционных моделей&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cистема \"Создание триангуляционных моделей\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Base_TriPath {
            get {
                return ((string)(this["Base_TriPath"]));
            }
            set {
                this["Base_TriPath"] = value;
            }
        }
        
        /// <summary>
        /// Система &quot;Морфологический анализ триангуляционных моделей&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система \"Морфологический анализ триангуляционных моделей\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Anal_MorPath {
            get {
                return ((string)(this["Anal_MorPath"]));
            }
            set {
                this["Anal_MorPath"] = value;
            }
        }
        
        /// <summary>
        /// Cистема &quot;Интегрированные генеративные технологии (классификация технологий, характеристики оборудования)&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cистема \"Интегрированные генеративные технологии (классификация технологий, харак" +
            "теристики оборудования)\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RP_TechnPath {
            get {
                return ((string)(this["RP_TechnPath"]));
            }
            set {
                this["RP_TechnPath"] = value;
            }
        }
        
        /// <summary>
        /// Система &quot;Статистическое моделирование рабочих процессов интегрированных технологий&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система \"Статистическое моделирование рабочих процессов интегрированных технологи" +
            "й\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Stat_Mod\\Stat_Mod.app")]
        public string Stat_Mod {
            get {
                return ((string)(this["Stat_Mod"]));
            }
            set {
                this["Stat_Mod"] = value;
            }
        }
        
        /// <summary>
        /// Программа для просмотра STL
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа для просмотра STL")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\App_0P\\GLC_Player_2_2_0\\glc_player.exe")]
        public string GLC_PlayerPuth {
            get {
                return ((string)(this["GLC_PlayerPuth"]));
            }
            set {
                this["GLC_PlayerPuth"] = value;
            }
        }
        
        /// <summary>
        /// Программа Magics
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа Magics")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Materialise\\Materialise Magics 21.0\\Magics.exe")]
        public string MagicsPuth {
            get {
                return ((string)(this["MagicsPuth"]));
            }
            set {
                this["MagicsPuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft Office\\Office12\\EXCEL.EXE")]
        public string ExcelPath {
            get {
                return ((string)(this["ExcelPath"]));
            }
            set {
                this["ExcelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public string RoundingKoord {
            get {
                return ((string)(this["RoundingKoord"]));
            }
            set {
                this["RoundingKoord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public string PositionResolution {
            get {
                return ((string)(this["PositionResolution"]));
            }
            set {
                this["PositionResolution"] = value;
            }
        }
        
        /// <summary>
        /// Многопоточная обработка данных
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Многопоточная обработка данных")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Multithreading {
            get {
                return ((bool)(this["Multithreading"]));
            }
            set {
                this["Multithreading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vanguard Si2 SLS")]
        public string NameEquipment {
            get {
                return ((string)(this["NameEquipment"]));
            }
            set {
                this["NameEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string SafeDistanceBody {
            get {
                return ((string)(this["SafeDistanceBody"]));
            }
            set {
                this["SafeDistanceBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string SafeDistanceBorder {
            get {
                return ((string)(this["SafeDistanceBorder"]));
            }
            set {
                this["SafeDistanceBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190.5")]
        public string WorkXmax {
            get {
                return ((string)(this["WorkXmax"]));
            }
            set {
                this["WorkXmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-190.5")]
        public string WorkXmin {
            get {
                return ((string)(this["WorkXmin"]));
            }
            set {
                this["WorkXmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165.1")]
        public string WorkYmax {
            get {
                return ((string)(this["WorkYmax"]));
            }
            set {
                this["WorkYmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-167.64")]
        public string WorkYmin {
            get {
                return ((string)(this["WorkYmin"]));
            }
            set {
                this["WorkYmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("457.2")]
        public string WorkZmax {
            get {
                return ((string)(this["WorkZmax"]));
            }
            set {
                this["WorkZmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.54")]
        public string WorkZmin {
            get {
                return ((string)(this["WorkZmin"]));
            }
            set {
                this["WorkZmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460")]
        public string WorkHeight {
            get {
                return ((string)(this["WorkHeight"]));
            }
            set {
                this["WorkHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("381")]
        public string WorkLength {
            get {
                return ((string)(this["WorkLength"]));
            }
            set {
                this["WorkLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("333")]
        public string WorkWidth {
            get {
                return ((string)(this["WorkWidth"]));
            }
            set {
                this["WorkWidth"] = value;
            }
        }
    }
}
