//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreAddTech {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class SettingsUser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUser defaultInstance = ((SettingsUser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUser())));
        
        public static SettingsUser Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Система FoxPro
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система FoxPro")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FoxProPath {
            get {
                return ((string)(this["FoxProPath"]));
            }
            set {
                this["FoxProPath"] = value;
            }
        }
        
        /// <summary>
        /// Программа Book
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа Book")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookPath {
            get {
                return ((string)(this["BookPath"]));
            }
            set {
                this["BookPath"] = value;
            }
        }
        
        /// <summary>
        /// Cистема &quot;Создание триангуляционных моделей&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cистема \"Создание триангуляционных моделей\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Base_TriPath {
            get {
                return ((string)(this["Base_TriPath"]));
            }
            set {
                this["Base_TriPath"] = value;
            }
        }
        
        /// <summary>
        /// Система &quot;Морфологический анализ триангуляционных моделей&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система \"Морфологический анализ триангуляционных моделей\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Anal_MorPath {
            get {
                return ((string)(this["Anal_MorPath"]));
            }
            set {
                this["Anal_MorPath"] = value;
            }
        }
        
        /// <summary>
        /// Cистема &quot;Интегрированные генеративные технологии (классификация технологий, характеристики оборудования)&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Cистема \"Интегрированные генеративные технологии (классификация технологий, харак" +
            "теристики оборудования)\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RP_TechnPath {
            get {
                return ((string)(this["RP_TechnPath"]));
            }
            set {
                this["RP_TechnPath"] = value;
            }
        }
        
        /// <summary>
        /// Система &quot;Статистическое моделирование рабочих процессов интегрированных технологий&quot;
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Система \"Статистическое моделирование рабочих процессов интегрированных технологи" +
            "й\"")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Stat_Mod\\Stat_Mod.app")]
        public string Stat_Mod {
            get {
                return ((string)(this["Stat_Mod"]));
            }
            set {
                this["Stat_Mod"] = value;
            }
        }
        
        /// <summary>
        /// Программа для просмотра STL
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа для просмотра STL")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e:\\App_0P\\GLC_Player_2_2_0\\glc_player.exe")]
        public string GLC_PlayerPuth {
            get {
                return ((string)(this["GLC_PlayerPuth"]));
            }
            set {
                this["GLC_PlayerPuth"] = value;
            }
        }
        
        /// <summary>
        /// Программа Magics
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Программа Magics")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\App\\Materialise\\Magics 19.01\\Magics.exe")]
        public string MagicsPuth {
            get {
                return ((string)(this["MagicsPuth"]));
            }
            set {
                this["MagicsPuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files (x86)\\MSOffice\\Office12\\EXCEL.EXE")]
        public string ExcelPath {
            get {
                return ((string)(this["ExcelPath"]));
            }
            set {
                this["ExcelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public float RoundingKoord {
            get {
                return ((float)(this["RoundingKoord"]));
            }
            set {
                this["RoundingKoord"] = value;
            }
        }
    }
}
