//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreAddTech {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings_AT : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_AT defaultInstance = ((Settings_AT)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_AT())));
        
        public static Settings_AT Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Путь к среде FoxPro
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Путь к среде FoxPro")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\0_VFP9\\vfp9.exe")]
        public string FoxProPath {
            get {
                return ((string)(this["FoxProPath"]));
            }
            set {
                this["FoxProPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Book\\Book.app")]
        public string BookPath {
            get {
                return ((string)(this["BookPath"]));
            }
            set {
                this["BookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Base_Tri\\Base_Tri.app")]
        public string Base_TriPath {
            get {
                return ((string)(this["Base_TriPath"]));
            }
            set {
                this["Base_TriPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Anal_Mor\\Anal_Mor.app")]
        public string Anal_MorPath {
            get {
                return ((string)(this["Anal_MorPath"]));
            }
            set {
                this["Anal_MorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\RP_Techn\\RP_Techn.app")]
        public string RP_TechnPath {
            get {
                return ((string)(this["RP_TechnPath"]));
            }
            set {
                this["RP_TechnPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Vfp50_D_Out_User\\Stat_Mod\\Stat_Mod.app")]
        public string Stat_Mod {
            get {
                return ((string)(this["Stat_Mod"]));
            }
            set {
                this["Stat_Mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\App_0P\\GLC_Player_2_2_0\\glc_player.exe")]
        public string GLC_PlayerPuth {
            get {
                return ((string)(this["GLC_PlayerPuth"]));
            }
            set {
                this["GLC_PlayerPuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Materialise\\Materialise Magics 21.0\\Magics.exe")]
        public string MagicsPuth {
            get {
                return ((string)(this["MagicsPuth"]));
            }
            set {
                this["MagicsPuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft Office\\Office12\\EXCEL.EXE")]
        public string ExcelPath {
            get {
                return ((string)(this["ExcelPath"]));
            }
            set {
                this["ExcelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public string RoundingKoord {
            get {
                return ((string)(this["RoundingKoord"]));
            }
            set {
                this["RoundingKoord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public string PositionResolution {
            get {
                return ((string)(this["PositionResolution"]));
            }
            set {
                this["PositionResolution"] = value;
            }
        }
        
        /// <summary>
        /// Многопоточная обработка данных
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Многопоточная обработка данных")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Multithreading {
            get {
                return ((bool)(this["Multithreading"]));
            }
            set {
                this["Multithreading"] = value;
            }
        }
    }
}
